
import React, { useEffect, useRef, useState } from 'react';
import Modal from '../../components/Modal';
import Styled from './chatStyle';
import { useRouter } from 'next/router';
import Head from 'next/head';


import io from 'socket.io-client';
const socket = io.connect("http://localhost:3002");

export default function Chat(){
    const router = useRouter();
    const [userAddress, setUserAddress] = useState(router.query.address);
    const [userId, setUserId] = useState(userAddress);
    //채팅 시작 전 socket server와 연동하기 위한 hook
    useEffect(()=>{
        socket.emit("init",{name: userAddress});
    });

    //Account의 address가 길어 이를 15글자로 표현.
    useEffect(()=>{
        setUserId(userAddress.slice(0,6)+"..."+userAddress.slice(userAddress.length-6,userAddress.length))
    },[userAddress]);

    //account의 변경을 통해 address를 바꿔주기 위한 hook
    useEffect(()=>{
        ethereum.on('accountsChanged', (accounts)=>{
            console.log(accounts);
            if(accounts.length>0)
                setUserAddress(accounts[0]);
            else
                setUserAddress("");
        })
    },[]);

    return (
        <Styled.Container>
            <Head>
                <title>Chat App using NextJS</title>
                <meta name="description" content="Generated by create next app, " />
            </Head>
            <Styled.Main>
                <Styled.Head>
                    <p style={{alignContents: 'center'}}> User : {userId}</p>
                </Styled.Head>
                <Styled.Log>
                {/* 중간 채팅 구간 */}
                <p>
                   
                    asdfasdfasdfasdf<br />
                    asdfasdfasdfasdf<br />
                    asdfasdfasdfasdf<br />
                    asdfasdfasdfasdf<br />
                   
                </p>
                </Styled.Log>
                <Styled.Input>
                        <textarea className='inputBox' />
                        <button className='submitBtn' style={{alignItems:'center',justifyContent:'center'}}>submmit</button>
                </Styled.Input>
            </Styled.Main>
        </Styled.Container>
    );
}