import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect } from 'react'
import Card from '../components/Card';

export default function Home() {
  const [userAddress, setUserAddress] = React.useState("");

  //Metamask와 연결하기 위한 JSON-RPC API
  //권한을 부여한 뒤 연결.
  async function connect(){
    if(typeof window.ethereum === 'undefined'){
      alert("error");
      return;
    }
    ethereum.request({
      method: 'wallet_requestPermissions',
      params: [{ eth_accounts:{}}]
    }).then((permissions)=>{
      console.log(permissions);
      setUserAddress(permissions[0].caveats[1].value[0]);
    });
  }

  //account의 변화를 감지하고 해당 account로 address를 변경해주는 Hook
  useEffect(()=>{
    window.ethereum.on("accountsChanged", accounts => {
      if(accounts.length>0) setUserAddress(accounts[0]);
      else setUserAddress("");
    })
  },[]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Test DApp using NextJS</title>
        <meta name="description" content="Generated by create next app, " />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Make Test DApp With <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by Add card in{' '}
          <code className={styles.code}>pages/index.js</code>
          <br/><br />
          {/* MetamaskConnect */}
        {
          userAddress ?
          <>
          <code className={styles.code}>
            Address: {userAddress}
          </code>
          {/* {'   '}
          <button className={styles.moveBtn} onClick={disConnect}>
            <a className={styles.moveText}>DisConnect</a>
          </button> */}
          </>
          :
          <button className={styles.moveBtn} onClick={connect}>
            <a className={styles.moveText}>Connect</a>
          </button>
        }
        </p>
        <div className={styles.grid}>
          <Card link={'/chat'} title={'Chat APP'} description={'Using Metamask Accounts, Enjoy Chat'} address={userAddress}></Card>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
